global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/alert.rules.yaml'

scrape_configs:
  - job_name: 'prometheus'
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'prometheus-jenkins'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins.local:443']
